---
roles:
  - name: arillso.restic
  - name: gantsign.golang
  - name: geerlingguy.docker
  - name: geerlingguy.ntp
  - name: geerlingguy.pip
  - name: geerlingguy.security
  - name: viasite-ansible.zsh
  - name: artis3n.tailscale
  - name: weareinteractive.users
  - name: t94j0.mythic
  #WarHorse Roles
  - name: iiitee.cobaltstrike_docker
  - name: almart.neo4j_docker
  - name: warhorse.traefik_docker
  - name: warhorse.nighthawk_docker
  - name: almart.gophish_docker
  - name: almart.evilginx2_docker
  - name: almart.nginx_docker
  - name: warhorse.parrotos_docker
  - name: almart.swag_docker

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
  - name: amazon.aws
  - name: community.docker
